image: gitlab-registry.cern.ch/mkwon/rooparticle:latest


defaultci:
    only:
        - develop
    script:
        - mkdir build
        - (cd build && cmake3 ../ && make -j $(nproc) all format-check)
