before_script:
 - yum update --yes
 - yum install --yes cmake3

defaultci:
    only:
        - develop
    script:
        - mkdir build
        - (cd build && cmake3 ../ && make -j $(nproc) all format-check)
