image: gitlab-registry.cern.ch/mkwon/rooparticle:latest

Build_Test:
    script:
        - source /~/~/root6/root/bin/thisroot.sh
        - mkdir build
        - (cd build && cmake3 ../ && make -j9)

Running_Test:
    script:
        - source /~/~/root6/root/bin/thisroot.sh
        - mkdir build
        - (cd build && cmake3 ../ && make -j9)
        - ./test_rutherford
        - ./test_collider_HeHe
        - ./test_3body_uniform 
