image: gitlab-registry.cern.ch/mkwon/rooparticle:latest

stages:
  - build
  - test

cache:
 paths:
   - /builds/mkwon/RooParticle/build
 key: "$CI_BUILD_REF"

build:
    stage: build
    script:
        - export
        - source /~/~/root6/root/bin/thisroot.sh
        - mkdir build
        - (cd build && cmake3 ../ && make -j9)

test:
    stage: test
    script:
        - pwd && ls
        - source /~/~/root6/root/bin/thisroot.sh
        - (cd build && ./test_rutherford)
        - (cd build && ./test_collider_HeHe)
        - (cd build && ./test_3body_uniform)
