image: gitlab-registry.cern.ch/mkwon/rooparticle:latest

stages:
  - build
  - test
  - qa

cache:
 paths:
   - /builds/mkwon/RooParticle/build
 key: "$CI_BUILD_REF"

build:
    stage: build
    script:
        - echo "push comment to " https://gitlab.cern.ch/api/v4/projects/${CI_PROJECT_PATH//\//%2F}/repository/commits/$CI_BUILD_REF/comments
        - curl --request POST --header "PRIVATE-TOKEN:$KEY_PLOT" --form "note=Nice picture man!" --form "author=AutoPlotter" https://gitlab.cern.ch/api/v4/projects/${CI_PROJECT_PATH//\//%2F}/repository/commits/$CI_BUILD_REF/comments
        - source /~/~/root6/root/bin/thisroot.sh
        - mkdir build
        - (cd build && cmake3 ../ && make -j9)

test:
    stage: test
    script:
        - source /~/~/root6/root/bin/thisroot.sh
        - (cd build && ./test_rutherford)
        - (cd build && ./test_collider_HeHe)
        - (cd build && ./test_3body_uniform)

qa_fixed:
    stage: qa
    script:
        - echo "Start QA Fixed Target"
qa_collide:
    stage: qa
    script:
        - echo "Start QA Colliding"
qa_3body:
    stage: qa
    script:
        - echo "Start QA 3body"
    
