image: gitlab-registry.cern.ch/mkwon/rooparticle:latest

stages:
  - build
  - test
  - qa

cache:
 paths:
   - /builds/mkwon/RooParticle/build
   - /data
 key: "$CI_BUILD_REF"

build:
    stage: build
    script:
        - source /base/root/bin/thisroot.sh
        - mkdir build
        - (cd build && cmake3 ../ && make -j9)

test:
    stage: test
    script:
        - export
        - source /base/root/bin/thisroot.sh
        - sh .gitlab/ci_test.sh
